[package]
name = "hdiff-apply"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.6"
tracing = "0.1.41"
tracing-subscriber = "0.3"
