[package]
name = "hdiff-apply"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.9"
tracing = "0.1.41"
tracing-subscriber = "0.3"
rayon = "1.10.0"
