[package]
name = "hdiff-apply"
version = "1.3.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.9"
rayon = "1.10.0"
crossterm = "0.28.1"
rand = "0.9.1"
md-5 = "0.10.6"
indicatif = "0.18.0"
regex = { version = "1.11.1", default-features = false, features = [
    "std",
    "unicode-perl",
] }

[profile.release]
strip = true
lto = true
opt-level = 3
codegen-units = 1
