// This file is @generated by prost-build.
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SophonPatchProto {
    #[prost(message, repeated, tag = "1")]
    pub patch_assets: ::prost::alloc::vec::Vec<SophonPatchAssetProperty>,
    #[prost(message, repeated, tag = "2")]
    pub unused_assets: ::prost::alloc::vec::Vec<SophonUnusedAssetProperty>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SophonPatchAssetProperty {
    #[prost(string, tag = "1")]
    pub asset_name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub asset_size: i64,
    #[prost(string, tag = "3")]
    pub asset_hash_md5: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub asset_infos: ::prost::alloc::vec::Vec<SophonPatchAssetInfo>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SophonPatchAssetInfo {
    #[prost(string, tag = "1")]
    pub version_tag: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub chunk: ::core::option::Option<SophonPatchAssetChunk>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SophonPatchAssetChunk {
    #[prost(string, tag = "1")]
    pub patch_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version_tag: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub build_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub patch_size: i64,
    #[prost(string, tag = "5")]
    pub patch_md5: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub patch_offset: i64,
    #[prost(int64, tag = "7")]
    pub patch_length: i64,
    #[prost(string, tag = "8")]
    pub original_file_name: ::prost::alloc::string::String,
    #[prost(int64, tag = "9")]
    pub original_file_length: i64,
    #[prost(string, tag = "10")]
    pub original_file_md5: ::prost::alloc::string::String,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SophonUnusedAssetProperty {
    #[prost(string, tag = "1")]
    pub version_tag: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub asset_infos: ::prost::alloc::vec::Vec<SophonUnusedAssetInfo>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SophonUnusedAssetInfo {
    #[prost(message, repeated, tag = "1")]
    pub assets: ::prost::alloc::vec::Vec<SophonUnusedAssetFile>,
}
#[derive(serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SophonUnusedAssetFile {
    #[prost(string, tag = "1")]
    pub file_name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub file_size: i64,
    #[prost(string, tag = "3")]
    pub file_md5: ::prost::alloc::string::String,
}
